/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/profiili/suosikit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Finds all Ohjaaja's suosikit */
    get: operations['ohjaajanSuosikkiFindAll'];
    put?: never;
    /** Add a new Ohjaaja's suosikki */
    post: operations['ohjaajanSuosikkiAdd'];
    /** Delete an Ohjaaja's suosikki */
    delete: operations['ohjaajanSuosikkiDelete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/profiili/kiinnostukset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Finds all Ohjaaja's kiinnostukset */
    get: operations['ohjaajanKiinnostusFindAll'];
    put?: never;
    /** Add a new Ohjaaja's kiinnostus */
    post: operations['ohjaajanKiinnostusAdd'];
    /** Delete an Ohjaaja's kiinnostus */
    delete: operations['ohjaajanKiinnostusDelete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/artikkeli/katselu/{artikkeliId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Adds a Katselu to the Artikkeli */
    post: operations['artikkelinKatseluAdd'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/profiili/ohjaaja': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ohjaajaGet'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/profiili/ohjaaja/vienti': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ohjaajaExport'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/artikkeli/viimeksi-katsellut': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Gets the last viewed article ids */
    get: operations['artikkelinKatseluGetMostRecentViewedArtikkeliIds'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    SuosikkiDto: {
      /** Format: uuid */
      readonly id?: string;
      /** Format: int64 */
      artikkeliId: number;
      /** Format: date-time */
      readonly luotu?: string;
    };
    KiinnostusDto: {
      /** Format: uuid */
      readonly id?: string;
      /** Format: int64 */
      asiasanaId?: number;
      /** Format: date-time */
      readonly luotu?: string;
    };
    CsrfTokenDto: {
      token: string;
      headerName: string;
      parameterName: string;
    };
    OhjaajaCsrfDto: {
      etunimi?: string;
      sukunimi?: string;
      csrf: components['schemas']['CsrfTokenDto'];
    };
    OhjaajaExportDto: {
      /** Format: uuid */
      id?: string;
      suosikit?: components['schemas']['OhjaajanSuosikkiExportDto'][];
      kiinnostukset?: components['schemas']['OhjaajanKiinnostusExportDto'][];
    };
    OhjaajanKiinnostusExportDto: {
      /** Format: uuid */
      id?: string;
      /** Format: date-time */
      luotu?: string;
      /** Format: int64 */
      asiasanaId?: number;
    };
    OhjaajanSuosikkiExportDto: {
      /** Format: uuid */
      id?: string;
      /** Format: date-time */
      luotu?: string;
      /** Format: int64 */
      artikkeliId?: number;
    };
    SivuDtoLong: {
      sisalto: number[];
      /**
       * Format: int64
       * @example 30
       */
      maara: number;
      /**
       * Format: int32
       * @example 3
       */
      sivuja: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  ohjaajanSuosikkiFindAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SuosikkiDto'][];
        };
      };
    };
  };
  ohjaajanSuosikkiAdd: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SuosikkiDto'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': string;
        };
      };
    };
  };
  ohjaajanSuosikkiDelete: {
    parameters: {
      query: {
        id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ohjaajanKiinnostusFindAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['KiinnostusDto'][];
        };
      };
    };
  };
  ohjaajanKiinnostusAdd: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['KiinnostusDto'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': string;
        };
      };
    };
  };
  ohjaajanKiinnostusDelete: {
    parameters: {
      query: {
        id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  artikkelinKatseluAdd: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        artikkeliId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ohjaajaGet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OhjaajaCsrfDto'];
        };
      };
    };
  };
  ohjaajaExport: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OhjaajaExportDto'];
        };
      };
    };
  };
  artikkelinKatseluGetMostRecentViewedArtikkeliIds: {
    parameters: {
      query?: {
        koko?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SivuDtoLong'];
        };
      };
    };
  };
}
